language: node_js
node_js: 10

services:
  - docker

install:
  - npm ci --ignore-scripts

script:
  - npx nps build
  - npx nps test.coverage -- -- --detectOpenHandles --forceExit
  - npx dockerize

after_success:
  - npm install codacy-coverage
  - npx codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
