name: CI
on:
  - push
  - pull_request
jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - run: echo "REF ${{ github.ref }}"
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci --ignore-scripts
    - name: Build
      run: npx nps build
    - name: Test
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        npx nps test.coverage
        npx codacy-coverage -v < ./coverage/lcov.info
  docker:
    name: Docker
    needs: ci
    runs-on: ubuntu-latest
    # Note: The `if` predicate seems to be supported here, but contexts are not
    # available, so we can't do things like inspect the current ref. When we try
    # to use the `github` context here, we get the following error:
    #
    # - Your workflow file was invalid: .github/workflows/ci.yml (Line: 31, Col: 9): Unrecognized named-value: 'github'. Located at position 12 within expression: startsWith(github.ref, 'refs/tags/v')
    # if: startsWith('foo', 'bar')
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v1
      # if: startsWith(github.ref, 'refs/tags/v')
    - uses: actions/setup-node@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        node-version: 10.x
    - name: Build & Push Docker Image
      # if: startsWith(github.ref, 'refs/tags/v')
      run: |
        npm ci
        echo ${{ secrets.DOCKER_PASSWORD}} | docker login --username ${{ secrets.DOCKER_LOGIN }} --password-stdin
        npx dockerize --push
